### PR TITLE
BTUC-14215: Submodule update qtquickcontrols

### PR DESCRIPTION
**Pull request by drusakov-broadsoft**
- Tabs removed

Change-Id: I043608e6adf7fe25da3bded239ac797c41bbde1d

### CODE REVIEW

**Comment by jmuhonen-broadsoft** [comment]
You need to update the value of this PR with the result of the submodule PR ( #3938785 )

**Review by jmuhonen-broadsoft — CHANGES_REQUESTED** [review]
Please update the submodule hash from submodule PR

**Comment by drusakov-broadsoft** [comment]
Done?

**Review by jmuhonen-broadsoft — APPROVED** [review]

**Comment by jmuhonen-broadsoft** [comment]
You can forcibly push to your own fork so that I don't need to squash the commits (so that we don't end up with broken commits).

**Pull request merged**
